"""Add checkin and exercise tables

Revision ID: 4b744cb9507b
Revises: 6518bbb20789
Create Date: 2026-05-28 20:38:53.982285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b744cb9507b'
down_revision: Union[str, Sequence[str], None] = '6518bbb20789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('q1_score', sa.Integer(), nullable=False),
    sa.Column('q2_score', sa.Integer(), nullable=False),
    sa.Column('alert_triggered', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_ins_created_at'), 'check_ins', ['created_at'], unique=False)
    op.create_index(op.f('ix_check_ins_id'), 'check_ins', ['id'], unique=False)
    op.create_index(op.f('ix_check_ins_user_id'), 'check_ins', ['user_id'], unique=False)
    op.create_table('exercise_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_completions_completed_at'), 'exercise_completions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_exercise_completions_id'), 'exercise_completions', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_completions_user_id'), 'exercise_completions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_completions_user_id'), table_name='exercise_completions')
    op.drop_index(op.f('ix_exercise_completions_id'), table_name='exercise_completions')
    op.drop_index(op.f('ix_exercise_completions_completed_at'), table_name='exercise_completions')
    op.drop_table('exercise_completions')
    op.drop_index(op.f('ix_check_ins_user_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_created_at'), table_name='check_ins')
    op.drop_table('check_ins')
    # ### end Alembic commands ###
