"""add user roles and core models

Revision ID: ae0e37686174
Revises: 4eae9da04c17
Create Date: 2025-12-24 20:14:29.284836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae0e37686174'
down_revision: Union[str, Sequence[str], None] = '4eae9da04c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('student', 'counsellor', 'admin', name='userrole'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('student', 'counsellor', 'admin', name='userrole'),
               existing_nullable=True)
    # ### end Alembic commands ###
