"""add approvals alerts flags and session notes

Revision ID: ea101648f72a
Revises: 557c792665f9
Create Date: 2026-06-11 23:11:55.698728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea101648f72a'
down_revision: Union[str, Sequence[str], None] = '557c792665f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('counsellor_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['counsellor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('check_ins', sa.Column('is_resolved', sa.Boolean(), nullable=True))
    op.add_column('journal_entries', sa.Column('is_flagged', sa.Boolean(), nullable=True))
    op.add_column('journal_entries', sa.Column('flag_reason', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_approved')
    op.drop_column('journal_entries', 'flag_reason')
    op.drop_column('journal_entries', 'is_flagged')
    op.drop_column('check_ins', 'is_resolved')
    op.drop_table('session_notes')
    # ### end Alembic commands ###
